let bank=[],quiz=[],index=0,score=0,answers=[],timer=null,seconds=0;
const $=id=>document.getElementById(id);
async function loadBank(){const res=await fetch("questions.json");bank=await res.json();[...new Set(bank.map(q=>q.category))].sort().forEach(c=>{let o=document.createElement("option");o.value=c;o.textContent=c;$("category").appendChild(o)})}
function filtered(){let c=$("category").value,d=$("difficulty").value;return bank.filter(q=>(c==="All"||q.category===c)&&(d==="All"||q.difficulty===d))}
function shuffle(a){return a.slice().sort(()=>Math.random()-.5)}
function startQuiz(){let pool=filtered(),n=+$("count").value;if(pool.length<n){alert(`Only ${pool.length} questions match these filters. Choose a broader filter.`);return}quiz=shuffle(pool).slice(0,n);index=0;score=0;answers=[];$("setup").classList.add("hidden");$("result").classList.add("hidden");$("quiz").classList.remove("hidden");seconds=n===100?3600:0;clearInterval(timer);if(seconds)timer=setInterval(()=>{seconds--;updateTimer();if(seconds<=0){clearInterval(timer);finishQuiz()}},1000);updateTimer();showQuestion()}
function updateTimer(){$("timer").textContent=seconds?`⏱ ${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`:""}
function showQuestion(){let q=quiz[index];$("progress").textContent=`Question ${index+1} of ${quiz.length}`;$("fill").style.width=`${index/quiz.length*100}%`;$("question").textContent=q.question;$("options").innerHTML="";$("explanation").classList.add("hidden");$("next").disabled=true;$("next").textContent=index===quiz.length-1?"Finish Quiz":"Next Question →";q.options.forEach(opt=>{let b=document.createElement("button");b.className="option";b.textContent=opt;b.onclick=()=>choose(opt,b);$("options").appendChild(b)})}
function choose(choice,clicked){let q=quiz[index];document.querySelectorAll(".option").forEach(b=>{b.disabled=true;if(b.textContent===q.answer)b.classList.add("correct")});let ok=choice===q.answer;if(ok)score++;else clicked.classList.add("wrong");answers.push({q,choice,ok});$("explanation").textContent=q.explanation;$("explanation").classList.remove("hidden");$("next").disabled=false}
function nextQuestion(){if(index<quiz.length-1){index++;showQuestion()}else finishQuiz()}
function finishQuiz(){clearInterval(timer);$("quiz").classList.add("hidden");$("result").classList.remove("hidden");let pct=Math.round(score/quiz.length*100);$("score").textContent=`${score} / ${quiz.length} (${pct}%)`;$("resultText").textContent=pct>=80?"Excellent work!":pct>=60?"Good progress — keep practising.":"Keep studying and try another random set.";$("review").innerHTML="<h3>Answer Review</h3>"+answers.map((a,i)=>`<div class="review-item"><b>${i+1}. ${a.q.question}</b><br><span class="${a.ok?"good":"bad"}">${a.ok?"✓ Correct":"✗ Incorrect"}</span> — Your answer: ${a.choice}<br>Correct answer: <b>${a.q.answer}</b><br><small>${a.q.explanation}</small></div>`).join("")}
loadBank().catch(e=>alert("Could not load questions.json. Make sure it is beside quiz.html."));
