name: Deploy HAM Corner

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Analytics to HTML pages
        run: |
          for file in *.html; do

            if ! grep -q 'js/analytics.js' "$file"; then

              sed -i 's#</body>#<script src="js/analytics.js"></script>\n</body>#' "$file"

            fi

          done

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
